SELECT * FROM customer;

--Q1. What is the total revenue generated by male vs. female customers?

SELECT c.gender, SUM(purchase_amount) AS revenue FROM customer c
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT c.customer_id, c.purchase_amount, c.discount_applied
FROM customer c
WHERE c.discount_applied = 'Yes' AND c.purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)
;

--Q3. Which are the top 5 products with the highest average review rating?

SELECT * FROM (
SELECT item_purchased, ROUND(AVG(review_rating)::NUMERIC,2) AS average_review_rating,
RANK() OVER (ORDER BY AVG(review_rating) DESC) AS rang
FROM customer
GROUP BY item_purchased)
WHERE rang <=5
;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT ROUND(AVG(purchase_amount), 2), shipping_type FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT subscription_status, COUNT(customer_id), ROUND(AVG(purchase_amount),2) AS avg_spend, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased, ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

SELECT Segment_customers, COUNT(*) AS "Number of Customers" FROM
(SELECT 
CASE 
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END AS Segment_customers
FROM customer) AS t
GROUP BY Segment_customers
ORDER BY "Number of Customers" DESC;

--Q8. What are the top 3 most purchased products within each category? 

WITH T AS (
SELECT category,item_purchased, COUNT(customer_id) AS "Number of Purchase",
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS rang
FROM customer
GROUP BY category,item_purchased
ORDER BY category, "Number of Purchase" DESC
)
SELECT T.* FROM T
WHERE rang IN(1,2,3)
;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status, COUNT(*) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
;

--Q10. What is the revenue contribution of each age group?

SELECT age_group, ROUND(SUM(purchase_amount) / (SELECT SUM(purchase_amount) FROM customer), 2) * 100 AS revenue_contribution
FROM customer
GROUP BY age_group;

-- Create views

CREATE VIEW Top_3_Products AS
SELECT * FROM
(WITH T AS (
SELECT category,item_purchased, COUNT(customer_id) AS "Number of Purchase",
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS rang
FROM customer
GROUP BY category,item_purchased
ORDER BY category, "Number of Purchase" DESC
)
SELECT T.* FROM T
WHERE rang IN(1,2,3)
)
;